/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DenLedXeMayRouteImport } from './routes/den-led-xe-may'
import { Route as XeSlugRouteImport } from './routes/xe.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DenLedXeMayRoute = DenLedXeMayRouteImport.update({
  id: '/den-led-xe-may',
  path: '/den-led-xe-may',
  getParentRoute: () => rootRouteImport,
} as any)
const XeSlugRoute = XeSlugRouteImport.update({
  id: '/xe/$slug',
  path: '/xe/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/den-led-xe-may': typeof DenLedXeMayRoute
  '/xe/$slug': typeof XeSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/den-led-xe-may': typeof DenLedXeMayRoute
  '/xe/$slug': typeof XeSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/den-led-xe-may': typeof DenLedXeMayRoute
  '/xe/$slug': typeof XeSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/dashboard' | '/den-led-xe-may' | '/xe/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dashboard' | '/den-led-xe-may' | '/xe/$slug'
  id: '__root__' | '/' | '/dashboard' | '/den-led-xe-may' | '/xe/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  DenLedXeMayRoute: typeof DenLedXeMayRoute
  XeSlugRoute: typeof XeSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/den-led-xe-may': {
      id: '/den-led-xe-may'
      path: '/den-led-xe-may'
      fullPath: '/den-led-xe-may'
      preLoaderRoute: typeof DenLedXeMayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/xe/$slug': {
      id: '/xe/$slug'
      path: '/xe/$slug'
      fullPath: '/xe/$slug'
      preLoaderRoute: typeof XeSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  DenLedXeMayRoute: DenLedXeMayRoute,
  XeSlugRoute: XeSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
